# Konfigurace pro PAdES PDF Signer
# Podporuje JSON i YAML formát

# TSA (Time Stamping Authority) - PostSignum
tsa_url: "http://tsa.postsignum.cz/tsp"
tsa_enabled: true

# PKCS#11 knihovny pro různé typy tokenů
pkcs11_libraries:
  isignum:
    - "C:\\Program Files\\iSignum\\pkcs11.dll"
    - "C:\\Program Files (x86)\\iSignum\\pkcs11.dll"
  
  postsignum:
    - "C:\\Program Files\\PostSignum\\pkcs11.dll"
    - "C:\\Program Files (x86)\\PostSignum\\pkcs11.dll"
  
  bit4id:
    - "C:\\Windows\\System32\\bit4xpki.dll"
    - "C:\\Program Files\\BIT4ID\\bit4xpki.dll"
  
  safenet:
    - "C:\\Windows\\System32\\eTPKCS11.dll"
    - "C:\\Program Files\\SafeNet\\Authentication\\SAC\\x64\\eTPKCS11.dll"

# Hash algoritmus
hash_algorithm: "SHA-256"

# Mechanism podpisu
signature_mechanism: "RSA_PKCS1v15"

# PAdES úroveň (PAdES-B, PAdES-B-LT, PAdES-B-LTA)
pades_level: "PAdES-B-LT"
